name: Test ExcelImporter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Repository auschecken
        uses: actions/checkout@v3

      - name: 🧰 PHP installieren
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: 📦 Composer-Abhängigkeiten installieren
        run: composer install

      - name: ✅ PHP-Dateien auf Syntax prüfen
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

